### PR TITLE
handle upload case for strapi-plugin-upload using FormData

### PR DESCRIPTION
**Pull request by yeung108**
- Handle changes in url for uploading files ("upload/files" instead of mere resource)
- Replace body with FormData for uploading file

### CODE REVIEW

**Comment by devalexandre** [comment]
its work?

**Comment by nazirov91** [comment]
@yeung108 @devalexandre This method will not work. I am working on a better solution. I will tag you guys when it is ready

**Comment by yeung108** [comment]
This should work as I use it in my project using Strapi Beta version. But of course I am open to better solution.😎

**Comment by devalexandre** [comment]
I'm trying to understand how to customize, the forms to upload.

**Comment by devalexandre** [comment]
> This method will not work. I am working on a better solution. I will tag you guys when it is ready

thanks

**Comment by nazirov91** [comment]
@yeung108 
There are several misunderstandings with this pull request:
1. There is no need to modify the GET methods
2. There is no need to convert the raw file into base64. Strapi can handle raw files without conversions
3. You dont have to update the delete functionality
4. File uploading should work for single/multiple files, and with single/multiple upload fields

But optimized file upload feature is embedded into the data provider now. Please take a look at the latest index/readme file. I do appreciate you for providing suggestions and effort.

Thank you!

**Comment by yeung108** [comment]
@nazirov91 Thank you for deploying the new optimised file upload feature, I have tested it and would like to ask a question:

The request link is different in strapi beta [](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html), for POST the link is /upload while others the links consist the extra wording "files" in the url; thus I added the checking in GET & DELETE methods. How do you tackle the changes in url? Coz when I tested it, it seems that there is no changing in url for different methods in upload. Do correct me if I missed something.

Thanks for the great effort anyway.

**Pull request closed without merging**
